CREATE TABLE user_profiles (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    age_range TEXT,
    sex TEXT,
    height_ft INTEGER,
    height_in INTEGER,
    weight_lbs REAL,
    physical_activity TEXT,
    energy_level TEXT,
    diet TEXT,
    meals_per_day TEXT,
    sleep_quality TEXT,
    stress_level TEXT,
    pregnant_or_breastfeeding TEXT,
    medical_conditions TEXT[],
    current_medications TEXT[],
    natural_supplements TEXT[],
    allergies TEXT[],
    health_goals TEXT[],
    other_health_goal TEXT,
    interested_supplements TEXT[],
    additional_info TEXT,
    security_question_1 TEXT,
    security_answer_1 TEXT,
    security_question_2 TEXT,
    security_answer_2 TEXT,
    security_question_3 TEXT,
    security_answer_3 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
