FORM_FIELDS = {
    "age_range": "18-24",
    "sex": "Male",
    "height_ft": 5,
    "height_in": 6,
    "weight_lbs": "",
    "physical_activity": "3-4 days",
    "energy_level": "Neutral",
    "diet": "I don't follow a specific diet",
    "meals_per_day": "3",
    "sleep_quality": "Good",
    "stress_level": "Moderate",
    "pregnant_or_breastfeeding": "No",
    "medical_conditions": "",
    "current_medications": "",
    "natural_supplements": "",
    "allergies": "",
    "health_goals": [],
    "other_health_goal": "",
    "interested_supplements": "",
    "security_answer_1": "",
    "security_answer_2": "",
    "security_answer_3": "",
    "additional_info": "",
    "load_user_id": ""
}